ALTER TABLE guests ADD COLUMN email VARCHAR(255) NULL;
ALTER TABLE guests DROP COLUMN phone_number;
ALTER TABLE user_passwords
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN role ENUM('owner', 'producer') NOT NULL DEFAULT 'owner';
